name: Deploy to Hostinger
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Hostinger via SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USERNAME }}
        port: ${{ secrets.HOSTINGER_PORT }}
        key: ${{ secrets.HOSTINGER_SSH_KEY }}
        source: "./*"
        target: "/home/u605899637/public_html"  # غيّر المسار لو مختلف
